In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 60

In [3]:
h1_res = pd.read_pickle("pickle/h1_res.pick")
h2_res = pd.read_pickle("pickle/h2_res.pick")
h1_dbd = pd.read_pickle("pickle/h1_dbd.pick")
h2_dbd = pd.read_pickle("pickle/h2_dbd.pick")

In [4]:
h1_res.head(5)

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,MEAL_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
2,2,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,False,False
3,3,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304,NaN,0,Transient,75.0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False
4,4,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,NaN,0,Transient,98.0,0,1,...,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False

## Get all variables in `hx_res` ready for modeling

In [5]:
h1_res.head(3)

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,MEAL_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
2,2,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,False,False

In [6]:
mask = h1_res.ADR == 0
h1_res[mask]

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,MEAL_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
125,125,0,32,2015,July,27,4,0,1,4,0,0,FB,PRT,Complementary,Direct,0,0,0,H,H,2,No Deposit,NaN,NaN,0,Transient,0.0,0,1,...,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
167,167,0,111,2015,July,28,6,0,0,2,0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,H,0,No Deposit,240,NaN,0,Transient,0.0,0,2,...,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
168,168,0,0,2015,July,28,6,0,0,1,0,0,BB,PRT,Direct,Direct,0,0,0,E,H,0,No Deposit,250,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39427,39427,0,6,2017,August,33,17,0,1,1,0,0,BB,PRT,Complementary,Corporate,0,0,0,A,E,0,No Deposit,302,NaN,0,Transient,0.0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
39527,39527,0,0,2017,August,34,20,0,0,2,0,0,BB,PRT,Direct,Direct,1,0,0,E,E,0,No Deposit,NaN,NaN,0,Transient,0.0,1,1,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
39585,39585,0,4,2017,August,34,20,2,0,1,0,0,BB,PRT,Complementary,Corporate,0,0,0,A,E,0,No Deposit,302,NaN,0,Transient,0.0,0,1,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
39852,39852,0,0,2017,August,35,30,0,0,2,0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,306,NaN,0,Transient,0.0,0,0,...,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
40016,40016,0,87,2017,August,35,30,2,4,2,0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,I,0,No Deposit,429,NaN,0,Transient,0.0,0,0,...,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,False,False,True,False,False,False,False,False,False,False,False,0,0,True,False

In [7]:
h1_res.Country.value_counts().head(20)

PRT    17630
GBR     6814
ESP     3957
IRL     2166
FRA     1611
DEU     1203
CN       710
NLD      514
USA      479
ITA      459
BEL      448
CHE      435
BRA      430
POL      333
SWE      304
AUT      210
RUS      189
ROU      177
FIN      151
CHN      134
Name: Country, dtype: int64

In [8]:
h1_res.RequiredCarParkingSpaces.value_counts()

0    34570
1     5462
2       25
8        2
3        1
Name: RequiredCarParkingSpaces, dtype: int64

In [9]:
h1_res.columns

Index(['ResNum', 'IsCanceled', 'LeadTime', 'ArrivalDateYear',
       'ArrivalDateMonth', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth',
       'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel',
       'IsRepeatedGuest', 'PreviousCancellations',
       'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType',
       'BookingChanges', 'DepositType', 'Agent', 'Company',
       'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces',
       'TotalOfSpecialRequests', 'ReservationStatus', 'ReservationStatusDate',
       'ArrivalDate', 'LOS', 'PreviousBookings', 'ResMadeDate', 'NumPeople',
       'CT_is_grp', 'CT_is_trn', 'CT_is_trnP', 'RS_No-Show', 'MS_Corporate',
       'MS_Direct', 'MS_Groups', 'MS_Offline TA/TO', 'MS_Online TA',
       'DC_Direct', 'DC_TA/TO', 'DC_Undefined', 'MEAL_FB', 'MEAL_HB',
       'MEAL_SC', 'MEAL_Undefined', 'FROM_PRT', 'FROM_GBR', 'FROM_ESP',
       'FROM_IRL', 'FROM_FRA', 'FROM_DEU', 'FROM_CN', 'FROM_NLD', 'FROM_USA',
       'FROM_ITA', 'FROM_other', 'DT_NonRefundable', 'DT_Refundable',
       'AgencyBooking', 'CompanyListed'],
      dtype='object')

In [10]:
h1_res.columns

Index(['ResNum', 'IsCanceled', 'LeadTime', 'ArrivalDateYear',
       'ArrivalDateMonth', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth',
       'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel',
       'IsRepeatedGuest', 'PreviousCancellations',
       'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType',
       'BookingChanges', 'DepositType', 'Agent', 'Company',
       'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces',
       'TotalOfSpecialRequests', 'ReservationStatus', 'ReservationStatusDate',
       'ArrivalDate', 'LOS', 'PreviousBookings', 'ResMadeDate', 'NumPeople',
       'CT_is_grp', 'CT_is_trn', 'CT_is_trnP', 'RS_No-Show', 'MS_Corporate',
       'MS_Direct', 'MS_Groups', 'MS_Offline TA/TO', 'MS_Online TA',
       'DC_Direct', 'DC_TA/TO', 'DC_Undefined', 'MEAL_FB', 'MEAL_HB',
       'MEAL_SC', 'MEAL_Undefined', 'FROM_PRT', 'FROM_GBR', 'FROM_ESP',
       'FROM_IRL', 'FROM_FRA', 'FROM_DEU', 'FROM_CN', 'FROM_NLD', 'FROM_USA',
       'FROM_ITA', 'FROM_other', 'DT_NonRefundable', 'DT_Refundable',
       'AgencyBooking', 'CompanyListed'],
      dtype='object')

In [11]:
h1_res.BookingChanges.value_counts()

0     32252
1      5469
2      1561
3       460
4       182
5        72
6        32
7        12
8         8
9         4
10        3
13        2
12        1
16        1
17        1
Name: BookingChanges, dtype: int64

In [12]:
X1_cols = [
    'LeadTime',
    'LOS',
    'StaysInWeekendNights',
    'StaysInWeekNights',
    'ADR',
    'NumPeople',
    'Adults',
    'Children',
    'Babies',
    'TotalOfSpecialRequests',
    'PreviousBookings',
    'PreviousCancellations',
    'PreviousBookingsNotCanceled',
    'BookingChanges',
    'DaysInWaitingList',
    'RequiredCarParkingSpaces',
    'IsRepeatedGuest',
    'AgencyBooking',
    'CompanyListed',
    'CT_is_grp',
    'CT_is_trn',
    'CT_is_trnP',
    'RS_No-Show',
    'MS_Corporate',
    'MS_Direct',
    'MS_Groups',
    'MS_Offline TA/TO',
    'MS_Online TA',
    'DC_Direct',
    'DC_TA/TO',
    'DC_Undefined',
    'FROM_PRT',
    'FROM_GBR',
    'FROM_ESP',
    'FROM_IRL',
    'FROM_FRA',
    'FROM_DEU',
    'FROM_CN',
    'FROM_NLD',
    'FROM_USA',
    'FROM_ITA',
    'FROM_other',
    'DT_NonRefundable',
    'DT_Refundable',
    'MEAL_Undefined',
    'MEAL_HB',
    'MEAL_FB',
]

In [13]:
X1_cxl = h1_res[X1_cols].copy()
y1_cxl = h1_res['IsCanceled']

In [14]:
len(X1_cols)

47

In [15]:
X1_cxl.describe()

,LeadTime,LOS,StaysInWeekendNights,StaysInWeekNights,ADR,NumPeople,Adults,Children,Babies,TotalOfSpecialRequests,PreviousBookings,PreviousCancellations,PreviousBookingsNotCanceled,BookingChanges,DaysInWaitingList,RequiredCarParkingSpaces,IsRepeatedGuest,CT_is_grp,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,DT_NonRefundable,DT_Refundable,MEAL_Undefined,MEAL_HB,MEAL_FB
count,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.00000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000
mean,92.675686,4.318547,1.189815,3.128732,94.952930,2.009735,1.867149,0.128682,0.013904,0.61977,0.248178,0.101722,0.146455,0.287968,0.527758,0.138068,0.044383,0.007089,0.754094,0.194483,0.007264,0.057639,0.162581,0.145681,0.186520,0.442561,0.196331,0.722042,0.000025,0.042911,0.003545,0.029181,0.200849,0.018822
std,97.285315,3.380273,1.147812,2.461329,61.442418,0.866054,0.697285,0.445195,0.118998,0.81393,1.686511,1.335115,1.001955,0.726548,7.428580,0.351001,0.205948,0.083900,0.430629,0.395807,0.084921,0.233062,0.368988,0.352791,0.389531,0.496696,0.397226,0.447998,0.004996,0.202658,0.059432,0.168316,0.400640,0.135897
min,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,2.000000,0.000000,1.000000,50.000000,2.000000,2.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,57.000000,3.000000,1.000000,3.000000,75.000000,2.000000,2.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,155.000000,7.000000,2.000000,5.000000,125.000000,2.000000,2.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,737.000000,69.000000,19.000000,50.000000,508.000000,55.000000,55.000000,10.000000,2.000000,5.00000,31.000000,26.000000,30.000000,17.000000,185.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
h2_res.columns

Index(['ResNum', 'IsCanceled', 'LeadTime', 'ArrivalDateYear',
       'ArrivalDateMonth', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth',
       'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel',
       'IsRepeatedGuest', 'PreviousCancellations',
       'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType',
       'BookingChanges', 'DepositType', 'Agent', 'Company',
       'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces',
       'TotalOfSpecialRequests', 'ReservationStatus', 'ReservationStatusDate',
       'ArrivalDate', 'LOS', 'PreviousBookings', 'ResMadeDate', 'NumPeople',
       'CT_is_grp', 'CT_is_trn', 'CT_is_trnP', 'RS_No-Show',
       'MS_Complementary', 'MS_Corporate', 'MS_Direct', 'MS_Groups',
       'MS_Offline TA/TO', 'MS_Online TA', 'MS_Undefined', 'DC_Direct',
       'DC_GDS', 'DC_TA/TO', 'DC_Undefined', 'MEAL_FB', 'MEAL_HB', 'MEAL_SC',
       'FROM_PRT', 'FROM_FRA', 'FROM_DEU', 'FROM_GBR', 'FROM_ESP', 'FROM_ITA',
       'FROM_BEL', 'FROM_BRA', 'FROM_USA', 'FROM_NLD', 'FROM_other',
       'DT_NonRefundable', 'DT_Refundable', 'AgencyBooking', 'CompanyListed'],
      dtype='object')

In [17]:
X2_cols = [
    'LeadTime',
    'LOS',
    'StaysInWeekendNights',
    'StaysInWeekNights',
    'ADR',
    'NumPeople',
    'Adults',
    'Children',
    'Babies',
    'TotalOfSpecialRequests',
    'PreviousBookings',
    'PreviousCancellations',
    'PreviousBookingsNotCanceled',
    'BookingChanges',
    'DaysInWaitingList',
    'RequiredCarParkingSpaces',
    'IsRepeatedGuest',
    'AgencyBooking',
    'CompanyListed',
    'CT_is_grp',
    'CT_is_trn',
    'CT_is_trnP',
    'RS_No-Show',
    'MS_Complementary',
    'MS_Corporate',
    'MS_Direct',
    'MS_Groups',
    'MS_Offline TA/TO',
    'MS_Online TA',
    'MS_Undefined',
    'DC_Direct',
    'DC_GDS',
    'DC_TA/TO',
    'DC_Undefined',
    'FROM_PRT',
    'FROM_FRA',
    'FROM_DEU',
    'FROM_GBR',
    'FROM_ESP',
    'FROM_ITA',
    'FROM_BEL',
    'FROM_BRA',
    'FROM_USA',
    'FROM_NLD',
    'FROM_other',
    'DT_NonRefundable',
    'DT_Refundable',
    'MEAL_FB',
    'MEAL_HB',
    'MEAL_SC',
]

In [18]:

X2_cxl = h2_res[X2_cols].copy()
y2_cxl = h2_res['IsCanceled']

In [19]:
X1_cxl.to_pickle("pickle/X1_cxl.pick")
y1_cxl.to_pickle("pickle/y1_cxl.pick")

X2_cxl.to_pickle("pickle/X2_cxl.pick")
y2_cxl.to_pickle("pickle/y2_cxl.pick")

In [20]:
X2_cxl.describe()

,LeadTime,LOS,StaysInWeekendNights,StaysInWeekNights,ADR,NumPeople,Adults,Children,Babies,TotalOfSpecialRequests,PreviousBookings,PreviousCancellations,PreviousBookingsNotCanceled,BookingChanges,DaysInWaitingList,RequiredCarParkingSpaces,IsRepeatedGuest,CT_is_grp,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Complementary,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,MS_Undefined,DC_Direct,DC_GDS,DC_TA/TO,DC_Undefined,DT_NonRefundable,DT_Refundable,MEAL_FB,MEAL_HB,MEAL_SC
count,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79326.000000,79330.000000,79326.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000,79330.000000
mean,109.735724,2.978142,0.795185,2.182957,105.304465,1.947268,1.850977,0.091370,0.004941,0.546918,0.212114,0.079743,0.132371,0.187369,3.226774,0.024367,0.025615,0.003693,0.748821,0.218492,0.011547,0.006832,0.037640,0.076806,0.176163,0.211106,0.488441,0.000025,0.085466,0.002433,0.869091,0.000050,0.162208,0.000252,0.000555,0.080890,0.133165
std,110.948526,1.862937,0.885026,1.456416,43.602954,0.636652,0.509292,0.372177,0.084323,0.780776,1.895271,0.415472,1.693411,0.608620,20.870890,0.154919,0.157983,0.060662,0.433694,0.413226,0.106834,0.082375,0.190326,0.266285,0.380961,0.408096,0.499870,0.005021,0.279575,0.049264,0.337303,0.007101,0.368644,0.015876,0.023545,0.272668,0.339755
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,2.000000,0.000000,1.000000,79.200000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,74.000000,3.000000,1.000000,2.000000,99.900000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,163.000000,4.000000,2.000000,3.000000,126.000000,2.000000,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,629.000000,57.000000,16.000000,41.000000,5400.000000,12.000000,4.000000,3.000000,10.000000,5.000000,78.000000,21.000000,72.000000,21.000000,391.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [23]:
h2_res[h2_res.NumPeople.isna()]

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,RS_No-Show,MS_Complementary,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,MS_Undefined,DC_Direct,DC_GDS,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,FROM_PRT,FROM_FRA,FROM_DEU,FROM_GBR,FROM_ESP,FROM_ITA,FROM_BEL,FROM_BRA,FROM_USA,FROM_NLD,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
540,540,1,2,2015,August,32,3,1,0,2,NaN,0,BB,PRT,Undefined,Undefined,0,0,0,B,B,0,No Deposit,NaN,NaN,0,Transient-Party,12.0,0,1,...,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
607,607,1,1,2015,August,32,5,0,2,2,NaN,0,BB,PRT,Direct,Undefined,0,0,0,B,B,0,No Deposit,14,NaN,0,Transient-Party,12.0,0,1,...,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
619,619,1,1,2015,August,32,5,0,2,3,NaN,0,BB,PRT,Undefined,Undefined,0,0,0,B,B,0,No Deposit,NaN,NaN,0,Transient-Party,18.0,0,2,...,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1100,1100,1,8,2015,August,33,13,2,5,2,NaN,0,BB,PRT,Online TA,Undefined,0,0,0,B,B,0,No Deposit,9,NaN,0,Transient-Party,76.5,0,1,...,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False