import pandas as pd
import numpy as np
import datetime

In [3]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 60

In [2]:
h1_res = pd.read_pickle("pickle/h1_res.pick")
h2_res = pd.read_pickle("pickle/h2_res.pick")
h1_dbd = pd.read_pickle("pickle/h1_dbd.pick")
h2_dbd = pd.read_pickle("pickle/h2_dbd.pick")

In [9]:
h1_dbd.shape

(793, 21)

In [4]:
h1_res.head(10)

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,ArrivalDate,LOS,PreviousBookings,CT_is_grp,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,2015-07-01,0,0,0,1,0,0,0,1,0,0,0,1,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,2015-07-01,0,0,0,1,0,0,0,1,0,0,0,1,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
2,2,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,...,2015-07-01,1,0,0,1,0,0,0,1,0,0,0,1,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,False,False
3,3,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304,NaN,0,Transient,75.0,0,0,...,2015-07-01,1,0,0,1,0,0,1,0,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False
4,4,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,NaN,0,Transient,98.0,0,1,...,2015-07-01,2,0,0,1,0,0,0,0,0,0,1,0,1,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False
5,5,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,NaN,0,Transient,98.0,0,1,...,2015-07-01,2,0,0,1,0,0,0,0,0,0,1,0,1,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False
6,6,0,0,2015,July,27,1,0,2,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,NaN,NaN,0,Transient,107.0,0,0,...,2015-07-01,2,0,0,1,0,0,0,1,0,0,0,1,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
7,7,0,9,2015,July,27,1,0,2,2,0,0,FB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,303,NaN,0,Transient,103.0,0,1,...,2015-07-01,2,0,0,1,0,0,0,1,0,0,0,1,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
8,8,1,85,2015,July,27,1,0,3,2,0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,NaN,0,Transient,82.0,0,1,...,2015-07-01,3,0,0,1,0,0,0,0,0,0,1,0,1,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
9,9,1,75,2015,July,27,1,0,3,2,0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15,NaN,0,Transient,105.5,0,0,...,2015-07-01,3,0,0,1,0,0,0,0,0,1,0,0,1,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False

In [5]:
h1_dbd.head(10)

,DOW,Occ,RoomsSold,ADR,RoomRev,RevPAR,Trn_RoomsSold,Trn_ADR,Trn_RoomRev,Grp_RoomsSold,Grp_ADR,Grp_RoomRev,TrnP_RoomsSold,TrnP_ADR,TrnP_RoomRev,Cnt_RoomsSold,Cnt_ADR,Cnt_RoomRev,WE,WD,STLY_Date
2015-07-01,Wed,0.19,36.0,93.25,3356.83,17.95,30.0,95.91,2877.25,0.0,0.0,0.0,0.0,0.00,0.00,6.0,79.93,479.58,False,True,2014-07-02
2015-07-02,Thu,0.34,64.0,97.68,6251.33,33.43,43.0,107.71,4631.34,0.0,0.0,0.0,2.0,75.23,150.46,19.0,77.34,1469.53,False,True,2014-07-03
2015-07-03,Fri,0.43,81.0,99.41,8052.35,43.06,54.0,109.70,5923.95,0.0,0.0,0.0,2.0,75.23,150.46,25.0,79.12,1977.94,True,False,2014-07-04
2015-07-04,Sat,0.58,108.0,96.98,10473.47,56.01,71.0,107.65,7643.08,0.0,0.0,0.0,5.0,74.37,371.86,32.0,76.83,2458.53,True,False,2014-07-05
2015-07-05,Sun,0.65,122.0,97.56,11901.72,63.65,79.0,105.76,8354.73,1.0,153.0,153.0,5.0,74.37,371.86,37.0,81.68,3022.13,False,True,2014-07-06
2015-07-06,Mon,0.76,142.0,101.05,14349.04,76.73,96.0,110.34,10592.48,0.0,0.0,0.0,3.0,83.75,251.26,43.0,81.52,3505.30,False,True,2014-07-07
2015-07-07,Tue,0.82,153.0,103.08,15771.44,84.34,103.0,112.27,11564.28,0.0,0.0,0.0,3.0,83.75,251.26,47.0,84.17,3955.90,False,True,2014-07-08
2015-07-08,Wed,0.84,157.0,104.77,16448.71,87.96,108.0,112.77,12178.80,0.0,0.0,0.0,5.0,96.29,481.46,44.0,86.10,3788.45,False,True,2014-07-09
2015-07-09,Thu,0.90,168.0,105.89,17790.31,95.14,114.0,113.10,12893.40,0.0,0.0,0.0,4.0,136.38,545.54,50.0,87.03,4351.37,False,True,2014-07-10
2015-07-10,Fri,0.95,177.0,108.87,19269.19,103.04,120.0,114.33,13719.88,0.0,0.0,0.0,6.0,156.59,939.54,51.0,90.39,4609.77,True,False,2014-07-11

## Vinny 1-1 3/4 Notes

* Possible model for only 750 days (only ~365 for training set?)
    *
*
*

3 models
* df_res
    * cxl forecast

* df_dbd (AS OF GIVEN DATE)
    * projected occ
    * rate recommendations

Features
* Rooms OTB at this time
* Rooms OTB STLY (by day of week)
* Recent trends (bookings) compared to same trend STLY
* Pace
* How many rooms left to sell
    * used as feature for proj. occ model
   
Rate Recc model
* uses projected occ, 
* time series model - lstm neural net (long shorttail model) - good for time series
    * lstm is data-hungry (try but may not have enough data)

## Vinny 1-1 3/10 Notes

**LSTM Model?**
* run simpler model first
    * Lr, RF
* create a GENR price
* add differentials based on ADR by booked room type

* try different prices until occ & ADr starts to make sense
* calculate rev at each price point based on remaining demand @ that price
    * record this for each price level & compare