In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 60

In [3]:
h1_res = pd.read_pickle("pickle/h1_res.pick")
h2_res = pd.read_pickle("pickle/h2_res.pick")
h1_dbd = pd.read_pickle("pickle/h1_dbd.pick")
h2_dbd = pd.read_pickle("pickle/h2_dbd.pick")

In [4]:
h1_res.head(5)

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,MEAL_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
2,2,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,False,False
3,3,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304,NaN,0,Transient,75.0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False
4,4,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,NaN,0,Transient,98.0,0,1,...,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False

## Get all variables in `hx_res` ready for modeling

In [5]:
h1_res.head(3)

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,MEAL_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
2,2,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,False,False

In [6]:
mask = h1_res.ADR == 0
h1_res[mask]

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,MEAL_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
125,125,0,32,2015,July,27,4,0,1,4,0,0,FB,PRT,Complementary,Direct,0,0,0,H,H,2,No Deposit,NaN,NaN,0,Transient,0.0,0,1,...,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
167,167,0,111,2015,July,28,6,0,0,2,0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,H,0,No Deposit,240,NaN,0,Transient,0.0,0,2,...,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
168,168,0,0,2015,July,28,6,0,0,1,0,0,BB,PRT,Direct,Direct,0,0,0,E,H,0,No Deposit,250,NaN,0,Transient,0.0,0,0,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39427,39427,0,6,2017,August,33,17,0,1,1,0,0,BB,PRT,Complementary,Corporate,0,0,0,A,E,0,No Deposit,302,NaN,0,Transient,0.0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
39527,39527,0,0,2017,August,34,20,0,0,2,0,0,BB,PRT,Direct,Direct,1,0,0,E,E,0,No Deposit,NaN,NaN,0,Transient,0.0,1,1,...,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False
39585,39585,0,4,2017,August,34,20,2,0,1,0,0,BB,PRT,Complementary,Corporate,0,0,0,A,E,0,No Deposit,302,NaN,0,Transient,0.0,0,1,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
39852,39852,0,0,2017,August,35,30,0,0,2,0,0,BB,PRT,Online TA,TA/TO,1,0,0,A,A,0,No Deposit,306,NaN,0,Transient,0.0,0,0,...,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,True,False
40016,40016,0,87,2017,August,35,30,2,4,2,0,0,HB,ESP,Online TA,TA/TO,0,0,0,D,I,0,No Deposit,429,NaN,0,Transient,0.0,0,0,...,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,False,False,True,False,False,False,False,False,False,False,False,0,0,True,False

In [7]:
h1_res.Country.value_counts().head(20)

PRT    17630
GBR     6814
ESP     3957
IRL     2166
FRA     1611
DEU     1203
CN       710
NLD      514
USA      479
ITA      459
BEL      448
CHE      435
BRA      430
POL      333
SWE      304
AUT      210
RUS      189
ROU      177
FIN      151
CHN      134
Name: Country, dtype: int64

In [8]:
h1_res.RequiredCarParkingSpaces.value_counts()

0    34570
1     5462
2       25
8        2
3        1
Name: RequiredCarParkingSpaces, dtype: int64

In [9]:
h1_res.columns

Index(['ResNum', 'IsCanceled', 'LeadTime', 'ArrivalDateYear',
       'ArrivalDateMonth', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth',
       'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel',
       'IsRepeatedGuest', 'PreviousCancellations',
       'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType',
       'BookingChanges', 'DepositType', 'Agent', 'Company',
       'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces',
       'TotalOfSpecialRequests', 'ReservationStatus', 'ReservationStatusDate',
       'ArrivalDate', 'LOS', 'PreviousBookings', 'ResMadeDate', 'NumPeople',
       'CT_is_grp', 'CT_is_trn', 'CT_is_trnP', 'RS_No-Show', 'MS_Corporate',
       'MS_Direct', 'MS_Groups', 'MS_Offline TA/TO', 'MS_Online TA',
       'DC_Direct', 'DC_TA/TO', 'DC_Undefined', 'MEAL_FB', 'MEAL_HB',
       'MEAL_SC', 'MEAL_Undefined', 'FROM_PRT', 'FROM_GBR', 'FROM_ESP',
       'FROM_IRL', 'FROM_FRA', 'FROM_DEU', 'FROM_CN', 'FROM_NLD', 'FROM_USA',
       'FROM_ITA', 'FROM_other', 'DT_NonRefundable', 'DT_Refundable',
       'AgencyBooking', 'CompanyListed'],
      dtype='object')

In [10]:
h1_res.columns

Index(['ResNum', 'IsCanceled', 'LeadTime', 'ArrivalDateYear',
       'ArrivalDateMonth', 'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth',
       'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel',
       'IsRepeatedGuest', 'PreviousCancellations',
       'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType',
       'BookingChanges', 'DepositType', 'Agent', 'Company',
       'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces',
       'TotalOfSpecialRequests', 'ReservationStatus', 'ReservationStatusDate',
       'ArrivalDate', 'LOS', 'PreviousBookings', 'ResMadeDate', 'NumPeople',
       'CT_is_grp', 'CT_is_trn', 'CT_is_trnP', 'RS_No-Show', 'MS_Corporate',
       'MS_Direct', 'MS_Groups', 'MS_Offline TA/TO', 'MS_Online TA',
       'DC_Direct', 'DC_TA/TO', 'DC_Undefined', 'MEAL_FB', 'MEAL_HB',
       'MEAL_SC', 'MEAL_Undefined', 'FROM_PRT', 'FROM_GBR', 'FROM_ESP',
       'FROM_IRL', 'FROM_FRA', 'FROM_DEU', 'FROM_CN', 'FROM_NLD', 'FROM_USA',
       'FROM_ITA', 'FROM_other', 'DT_NonRefundable', 'DT_Refundable',
       'AgencyBooking', 'CompanyListed'],
      dtype='object')

In [11]:
h1_res.BookingChanges.value_counts()

0     32252
1      5469
2      1561
3       460
4       182
5        72
6        32
7        12
8         8
9         4
10        3
13        2
12        1
16        1
17        1
Name: BookingChanges, dtype: int64

In [12]:
X1_cols = [
    'ArrivalDate',
    'ReservationStatusDate',
    'LeadTime',
    'LOS',
    'StaysInWeekendNights',
    'StaysInWeekNights',
    'ADR',
    'NumPeople',
    'Adults',
    'Children',
    'Babies',
    'TotalOfSpecialRequests',
    'PreviousBookings',
    'PreviousCancellations',
    'PreviousBookingsNotCanceled',
    'BookingChanges',
    'DaysInWaitingList',
    'RequiredCarParkingSpaces',
    'IsRepeatedGuest',
    'AgencyBooking',
    'CompanyListed',
    'CT_is_grp',
    'CT_is_trn',
    'CT_is_trnP',
    'RS_No-Show',
    'MS_Corporate',
    'MS_Direct',
    'MS_Groups',
    'MS_Offline TA/TO',
    'MS_Online TA',
    'DC_Direct',
    'DC_TA/TO',
    'DC_Undefined',
    'FROM_PRT',
    'FROM_GBR',
    'FROM_ESP',
    'FROM_IRL',
    'FROM_FRA',
    'FROM_DEU',
    'FROM_CN',
    'FROM_NLD',
    'FROM_USA',
    'FROM_ITA',
    'FROM_other',
    'DT_NonRefundable',
    'DT_Refundable',
    'MEAL_Undefined',
    'MEAL_HB',
    'MEAL_FB',
]

In [13]:
X1_cxl = h1_res[X1_cols].copy()
y1_cxl = h1_res['IsCanceled']

In [14]:
len(X1_cols)

49

In [15]:
h2_res.Country.value_counts().head(20)

PRT    30960
FRA     8804
DEU     6084
GBR     5315
ESP     4611
ITA     3307
BEL     1894
BRA     1794
USA     1618
NLD     1590
CHE     1295
IRL     1209
AUT     1053
CHN      865
SWE      720
ISR      641
POL      586
CN       569
NOR      484
RUS      443
Name: Country, dtype: int64

In [16]:
meal_cols = list(pd.get_dummies(h1_res.Meal, drop_first=True).columns)
meal_cols = ["MEAL_" + ms_name for ms_name in meal_cols]
h1_res[meal_cols] = pd.get_dummies(h1_res.Meal, drop_first=True)
h1_res

,ResNum,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,Meal,Country,MarketSegment,DistributionChannel,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,ReservedRoomType,AssignedRoomType,BookingChanges,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,...,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,MEAL_FB,MEAL_HB,MEAL_SC,MEAL_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,AgencyBooking,CompanyListed,MEAL_FB,MEAL_HB,MEAL_SC
0,0,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,...,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False,0,0,0
1,1,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,...,0,1,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,0,0,False,False,0,0,0
2,2,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,...,0,1,0,0,0,1,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,False,False,0,0,0
3,3,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304,NaN,0,Transient,75.00,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False,0,0,0
4,4,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,NaN,0,Transient,98.00,0,1,...,0,0,0,0,1,0,1,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40055,40055,0,212,2017,August,35,31,2,8,2,1,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,1,No Deposit,143,NaN,0,Transient,89.75,0,0,...,0,0,0,1,0,0,1,0,0,0,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False,0,0,0
40056,40056,0,169,2017,August,35,30,2,9,2,0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250,NaN,0,Transient-Party,202.27,0,1,...,0,1,0,0,0,1,0,0,0,0,0,0,False,False,False,True,False,False,False,False,False,False,False,0,0,True,False,0,0,0
40057,40057,0,204,2017,August,35,29,4,10,2,0,0,BB,IRL,Direct,Direct,0,0,0,E,E,0,No Deposit,250,NaN,0,Transient,153.57,0,3,...,0,1,0,0,0,1,0,0,0,0,0,0,False,False,False,True,False,False,False,False,False,False,False,0,0,True,False,0,0,0
40058,40058,0,211,2017,August,35,31,4,10,2,0,0,HB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,40,NaN,0,Contract,112.80,0,1,...,0,0,0,1,0,0,1,0,0,1,0,0,False,True,False,False,False,False,False,False,False,False,False,0,0,True,False,0,1,0
40059,40059,0,161,2017,August,35,31,4,10,2,0,0,HB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,69,NaN,0,Transient,99.06,0,0,...,0,0,0,1,0,0,1,0,0,1,0,0,False,False,False,False,False,True,False,False,False,False,False,0,0,True,False,0,1,0