# Setup Future DBD DataFrames

This DataFrame will be used for predicting demand and ultimately recommending rates.

This notebooks makes use of the `generate_hotel_dfs` and `model_cancellations` functions found in `utils.py`.

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 70

In [3]:
h1_futures = pd.read_pickle("pickle/h1_futures.pick")
h2_futures = pd.read_pickle("pickle/h2_futures.pick")

In [4]:
h1_futures.head(3)

,LeadTime,LOS,StaysInWeekendNights,StaysInWeekNights,ADR,NumPeople,Adults,Children,Babies,TotalOfSpecialRequests,PreviousBookings,PreviousCancellations,PreviousBookingsNotCanceled,BookingChanges,DaysInWaitingList,RequiredCarParkingSpaces,IsRepeatedGuest,AgencyBooking,CompanyListed,CT_is_grp,CT_is_trn,CT_is_trnP,RS_No-Show,MS_Corporate,MS_Direct,MS_Groups,MS_Offline TA/TO,MS_Online TA,DC_Direct,DC_TA/TO,DC_Undefined,FROM_PRT,FROM_GBR,FROM_ESP,FROM_IRL,FROM_FRA,FROM_DEU,FROM_CN,FROM_NLD,FROM_USA,FROM_ITA,FROM_other,DT_NonRefundable,DT_Refundable,MEAL_Undefined,MEAL_HB,MEAL_FB,will_cancel
12815,240,16,5,11,183.05,2,2,0,0,0,0,0,0,0,0,0,0,True,False,0,1,0,0,0,0,0,0,1,0,1,0,False,False,False,False,False,False,False,False,False,False,True,0,0,0,1,0,NaN
12816,236,16,5,11,182.92,2,2,0,0,0,0,0,0,0,0,0,0,True,False,0,1,0,0,0,0,0,0,1,0,1,0,True,False,False,False,False,False,False,False,False,False,False,0,0,0,1,0,NaN
12859,202,14,4,10,158.63,3,2,1,0,0,0,0,0,0,0,0,0,True,False,0,1,0,0,0,0,0,1,0,0,1,0,True,False,False,False,False,False,False,False,False,False,False,0,0,0,0,0,NaN